# Generated by Django 4.2.4 on 2023-10-28 04:30

import django.contrib.postgres.fields
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # hstore 확장
        HStoreExtension(),

        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoo_name', models.CharField(max_length=10)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnimalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_field', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), null=True, size=None)),
                ('zoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.zoo')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('info', models.TextField()),
                ('age', models.IntegerField()),
                ('medical_check', models.BooleanField()),
                ('birth_at', models.DateTimeField(auto_now=True)),
                ('zoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.zoo')),
            ],
        ),
    ]
